orbs:
  cxflow: mp-namespace/cx-scanner-orb@dev:alpha
version: 2.1
workflows:
  sast-scan:
    jobs:
      - cxflow/scan:
          filters:
            branches:
              only:
                - master
          preset: Checkmarx Express
          project: CxProject
          report-file: vulns.json
          team: \CxServer\SP\Checkmarx\Mithilesh
  version: 2