version: 2.1
orbs:
  cxflow: checkmarx-ts/cxflow@1.0.5

workflows:
  version: 2
  sca-scan:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master

jobs:
  cx-scan:
    executor: cxflow/latest
    steps:
      - checkout
      - cxflow/scan:
          project: CircleCI-GH-SCA-MP
          sca-accessControlUrl: https://platform.checkmarx.net
          sca-apiUrl: https://api.scacheckmarx.com
          sca-appUrl: https://sca.scacheckmarx.com
          report-file: checkmarx.json
          scanners: sca
      - store_artifacts:
          path: checkmarx.json
