version: 2.1

orbs:
  cxflow: checkmarx-ts/cxflow@1.0.4

jobs:
  cx-scan:
    executor: cxflow/default
    steps:
      - checkout
      - cxflow/scan:
          preset: Checkmarx Express
          report-file: checkmarx.json
          team: /CxServer/MP
      - store_artifacts:
          path: checkmarx.json
orbs:
  cxflow: checkmarx-ts/cxflow@1.0.4
version: 2.1
workflows:
  sast-scan:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
  version: 2